//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antecedent
    {
        public int ID_Antecedent { get; set; }
        public string description { get; set; }
        public Nullable<int> ID_Consultation { get; set; }
        public Nullable<int> ID_Patient { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
