//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPAtient
    {
        public int ID_ContactPatient { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string sexe { get; set; }
        public string profession { get; set; }
        public string situation_familial { get; set; }
        public string groupe_sanguin { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public Nullable<int> ID_PATIENT { get; set; }
    }
}
